version: '3.8'

services:
  frontend:
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    ports:
      - "80:80"
    restart: unless-stopped

  backend:
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=devsecops
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    secrets:
      - db_root_password
      - db_password

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      - DB_HOST=backend
      - DB_USER=app_user
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_NAME=devsecops
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    secrets:
      - db_password

  monitoring:
    ports:
      - "9090:9090"
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - prometheus_data:/prometheus
    restart: unless-stopped

volumes:
  mariadb_data:
  grafana_data:
  prometheus_data:

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
