apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
    secureJsonData:
      httpHeaderValue1: "Bearer ${PROMETHEUS_API_TOKEN}"
    securitySettings:
      tlsSkipVerify: false
      tlsAuth: false
      tlsAuthWithCACert: false
