global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

  external_labels:
    monitor: 'devsecops-monitoring'

# Règles d'alerting
rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']

# Configuration de la sécurité TLS
tls_config:
  cert_file: /etc/prometheus/certs/prometheus.crt
  key_file: /etc/prometheus/certs/prometheus.key
  ca_file: /etc/prometheus/certs/ca.crt

# Configuration de l'authentification basique
basic_auth_config:
  username: ${PROMETHEUS_USER}
  password: ${PROMETHEUS_PASSWORD}
